In [48]:
## Create a notebook to  transform data on sheet in wide format to long format

In [61]:
# Import librarries
import pandas as pd 
import os
import re
pd.options.display.max_rows = 10
pd.options.display.max_columns = None

In [62]:
# Read Excel file from local path
print(os.getcwd())
path_to_file = "C:\projects\deeksha\GridExport_January_18_2024_11_48_39.xlsx"

c:\Users\91888\Downloads

In [63]:
data = pd.read_excel(path_to_file, )

In [64]:
col_names = data.columns
col_names=col_names.drop('Company Name')




col_names_list = []
for colname in col_names:
    col_names_list.append(re.sub( '(\d+)', '',colname))
    #print(col_names_list)

col_names_list= list(set(col_names_list))

In [65]:
data.head

<bound method NDFrame.head of                            Company Name    TQ2014    TQ2015    TQ2016  \
0                            A C C Ltd.  2.130143  2.274329  1.989409
1                A I A Engineering Ltd.  3.184262  5.879729  3.713890
2                Adani Enterprises Ltd.  2.073602  3.236987  1.014415
3    Aditya Birla Fashion & Retail Ltd.  0.846405  1.110068  2.854654
4      Apollo Hospitals Enterprise Ltd.  1.307606  3.561873  2.719388
..                                  ...       ...       ...       ...
102                        Vedanta Ltd.  1.093700  1.151064  0.378407
103                  Vodafone Idea Ltd.  1.441966  1.556344  0.990627
104                          Wipro Ltd.  2.993787  2.983430  2.467764
105  Zee Entertainment Enterprises Ltd.  5.887102  6.168629  6.258812
106             Zydus Lifesciences Ltd.  3.471906  4.803872  3.467637

       TQ2017    TQ2018    TQ2019    TQ2020    TQ2021     TQ2022    TQ2023  \
0    1.968837  1.859990  1.927302  1.046650  1.942161   1.909578  1.356062
1    5.324023  4.276345  4.728722  3.317099  3.181010   2.424446  3.462167
2    1.284282  1.523862  1.271418  1.288892  8.820712  10.409398  5.041363
3    2.752733  2.345789  2.825225  1.758160  2.250832   2.704528  1.650505
4    2.232489  1.928409  2.046010  1.744502  3.952676   5.676662  5.157347
..        ...       ...       ...       ...       ...        ...       ...
102  0.742770  0.926217  0.693256  0.484367  0.859805   1.260734  0.929859
103  0.857412  0.823500  0.705233  0.594940  1.020157   1.154961  1.149465
104  2.067202  2.262218  2.356139  1.789483  3.514166   4.070388  2.392603
105  6.951329  6.127722  3.964429  1.130219  1.674709   2.196700  1.556946
106  4.023682  3.118732  2.572483  1.701020  2.423200   1.908328  2.349779

       ESGC2014    ESGC2015    ESGC2016    ESGC2017    ESGC2018    ESGC2019  \
0     57.142857   64.285714  100.000000   43.750000  100.000000  100.000000
1     43.333333  100.000000   73.728814  100.000000   89.655172   88.461538
2     33.750000  100.000000   24.545455   15.853659   87.500000   42.222222
3     41.463415  100.000000   40.243902  100.000000  100.000000  100.000000
4     48.666667  100.000000   59.420290  100.000000  100.000000   72.727273
..          ...         ...         ...         ...         ...         ...
102  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000
103  100.000000  100.000000  100.000000  100.000000  100.000000         NaN
104   77.160494   76.644737  100.000000   65.340909  100.000000  100.000000
105   37.500000   33.333333   79.310345  100.000000  100.000000  100.000000
106  100.000000  100.000000  100.000000  100.000000  100.000000         NaN

       ESGC2020    ESGC2021    ESGC2022    ESGC2023     BI2014     BI2015  \
0    100.000000  100.000000   55.555556   41.666667  50.000000  64.285714
1    100.000000  100.000000   88.333333   92.307692  50.000000  40.000000
2     21.875000   18.627451   26.923077   17.391304  44.444444  50.000000
3    100.000000   48.076923   57.608696   54.651163  40.000000  60.000000
4     52.272727  100.000000  100.000000  100.000000  66.666667  61.538462
..          ...         ...         ...         ...        ...        ...
102  100.000000  100.000000  100.000000         NaN  40.000000  55.555556
103         NaN         NaN         NaN         NaN  50.000000  58.333333
104  100.000000  100.000000  100.000000         NaN  76.923077  77.777778
105         NaN         NaN         NaN         NaN  55.555556  50.000000
106         NaN         NaN         NaN         NaN  66.666667  50.000000

        BI2016     BI2017     BI2018     BI2019     BI2020     BI2021  \
0    66.666667  42.857143  53.846154  50.000000  56.250000  50.000000
1    44.444444  40.000000  40.000000  44.444444  55.555556  55.555556
2    50.000000  50.000000  50.000000  50.000000  50.000000  50.000000
3    60.000000  66.666667  57.142857  57.142857  57.142857  50.000000
4    61.538462  66.666667  58.333333  50.000000  50.000000  50.000000
..         ...        ...        ...        ...        ...        ...
102  50.000000  50.000000  54.545455  50.000000  55.555556  44.444444
103  54.545455  50.000000  54.545455  42.857143  45.454545  46.153846
104  63.636364  70.000000  70.000000  72.727273  66.666667  66.666667
105  55.555556  50.000000  50.000000  50.000000  57.142857  80.000000
106  50.000000  57.142857  50.000000  55.555556  50.000000  50.000000

        BI2022     BI2023  BS2014  BS2015  BS2016  BS2017  BS2018  BS2019  \
0    50.000000  50.000000      12      14      12      14      13      12
1    55.555556  55.555556       8      10       9      10      10       9
2    50.000000  62.500000       9      10      10      10      10       8
3    50.000000  50.000000       5       5       5       6       7       7
4    54.545455  54.545455      15      13      13      15      12      10
..         ...        ...     ...     ...     ...     ...     ...     ...
102  50.000000  50.000000      10       9       8       8      11      10
103  50.000000  54.545455      14      12      11      12      11      14
104  66.666667  55.555556      13       9      11      10      10      11
105  62.500000  57.142857       9       8       9       8       8       8
106  50.000000  60.000000       6       6       6       7       8       9

     BS2020  BS2021  BS2022  BS2023  CD2014  CD2015  CD2016  CD2017  CD2018  \
0        16      12      12       8       0       0       0       0       0
1         9       9       9       9       0       0       0       0       0
2         8       8       8       8       0       0       0       0       0
3         7      14      12      14       0       0       0       0       0
4        10      10      11      11       1       1       1       1       1
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
102       9       9       8       8       0       0       0       0       0
103      11      13      12      11       0       0       0       0       0
104       9       9       9       9       0       0       0       0       0
105       7      10       8       7       0       0       0       0       0
106       8       8       8      10       0       0       0       0       0

     CD2019  CD2020  CD2021  CD2022  CD2023  GD2014  GD2015  GD2016  GD2017  \
0         0       0       0       0       0       1       1       1       1
1         0       0       0       0       0       0       0       0       0
2         0       0       0       0       0       0       0       0       0
3         0       0       0       0       0       0       0       0       0
4         1       1       1       1       1       0       0       0       0
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
102       0       0       0       0       0       0       0       0       0
103       0       0       0       0       0       0       0       0       0
104       0       0       0       0       0       0       0       0       0
105       0       0       0       0       0       1       1       1       1
106       0       0       0       0       0       0       0       0       0

     GD2018  GD2019  GD2020  GD2021  GD2022  GD2023   ESGS2014   ESGS2015  \
0         1       1       1       1       1       0  75.716704  72.143195
1         0       0       0       0       0       0  87.186315  87.405931
2         0       0       0       0       0       0  78.874422  80.656516
3         0       0       0       0       0       0  58.136410  52.338181
4         0       0       0       0       0       0  85.693849  82.767523
..      ...     ...     ...     ...     ...     ...        ...        ...
102       0       0       0       0       0       0  62.236011  47.935652
103       0       0       1       1       1       1  73.103987  78.379834
104       0       0       1       1       1       1  50.799460  46.923936
105       1       1       1       1       1       1  52.951324  54.421977
106       0       0       0       0       0       0  63.013979  54.091589

      ESGS2016   ESGS2017   ESGS2018   ESGS2019   ESGS2020   ESGS2021  \
0    77.404699  74.267736  75.441160  77.456287  73.431522  76.646872
1    87.210108  87.359326  88.547975  89.290501  89.336400  92.494782
2    80.434191  72.689114  76.768855  79.138517  74.945533  78.269017
3    61.821751  63.766993  66.405258  73.162860  70.724764  70.841086
4    83.307863  72.123904  73.576737  63.050132  42.505180  43.606367
..         ...        ...        ...        ...        ...        ...
102  43.241529  43.418288  41.256793  34.052633  31.715088  35.308618
103  76.071434  68.562817  74.519144        NaN        NaN        NaN
104  35.123460  30.217736  36.364371  38.495379  37.813704  27.778533
105  53.193340  46.553366  45.715222  45.839946        NaN        NaN
106  50.638273  51.356962  46.395199        NaN        NaN        NaN

      ESGS2022   ESGS2023   LTA2014   LTA2015   LTA2016   LTA2017   LTA2018  \
0    75.262886  75.659417  5.091727  5.111278  5.115916  5.140439  5.183320
1    89.453142  91.049437  4.228447  4.306322  4.386040  4.453222  4.506084
2    80.149007  81.894713  5.355831  5.357331  5.164937  5.173537  5.195157
3    58.876437  59.237247  4.333090  4.330911  4.661269  4.703225  4.760124
4    43.109548  31.513363  4.686335  4.764922  4.884140  4.929222  4.965302
..         ...        ...       ...       ...       ...       ...       ...
102  31.934218        NaN  5.938112  5.911287  6.262907  6.235531  6.191635
103        NaN        NaN  5.653995  5.772104  5.908367  6.001336  6.043723
104  20.596329        NaN  5.665396  5.733103  5.772712  5.804109  5.769281
105        NaN        NaN  4.678518  4.751949  4.793238  4.887420  4.967052
106        NaN        NaN  4.813000  4.887932  4.987148  5.078326  5.124641

      LTA2019   LTA2020   LTA2021   LTA2022   LTA2023    TA2014    TA2015  \
0    5.212023  4.888067  4.892150  4.911850  5.365492  123517.2  129204.7
1    4.557437  4.974435  5.055186  5.164027  4.906012   16921.8   20245.2
2    5.174581  5.296483  5.342652  5.397391  5.604215  226898.1  227683.2
3    4.821868  5.025312  5.102884  5.155310  5.197623   21532.3   21424.5
4    4.997635  5.861650  5.892636  5.964940  5.097195   48566.3   58199.9
..        ...       ...       ...       ...       ...       ...       ...
102  6.203520       NaN       NaN       NaN  6.220858  867185.9  815243.3
103  6.403084       NaN       NaN       NaN  6.364761  450811.1  591703.8
104  5.828848       NaN       NaN       NaN  5.936692  462803.0  540882.0
105  5.044312       NaN       NaN       NaN  5.122956   47700.0   56487.0
106  5.181961       NaN       NaN       NaN  5.366008   65013.0   77256.0

        TA2016     TA2017     TA2018     TA2019     TA2020     TA2021  \
0     130591.7   138178.0   152517.5   162938.1   174282.7   184552.6
1      24324.3    28393.7    32068.9    36094.2    39984.8    61460.1
2     146196.5   149120.4   156731.6   149479.4   140921.7   131878.0
3      45842.6    50492.3    57560.4    66354.1    97135.8    99398.2
4      76584.4    84961.5    92321.3    99457.0   117913.0   113314.0
..         ...        ...        ...        ...        ...        ...
102  1831920.9  1720010.0  1554660.0  1597790.0  1453820.0  1434730.0
103   809779.4  1003080.1  1105919.0  2529788.0  2536319.0  2238491.0
104   592532.0   636955.0   587870.0   674292.0   661307.0   665430.0
105    62121.0    77165.0    92694.0   110742.0   111143.0   118978.0
106    97084.0   119764.0   133242.0   152041.0   182597.0   202446.0

        TA2022     TA2023  DER2014  DER2015  DER2016  DER2017  DER2018  \
0     212220.7   232002.1     0.00     0.00     0.00     0.01     0.01
1      63155.1    80540.1     0.09     0.05     0.08     0.06     0.04
2     217106.5   401989.6     0.66     0.59     1.89     1.91     1.71
3     118946.5   157624.2     1.82     3.80     2.04     2.13     1.70
4     119247.0   125082.0     0.36     0.53     0.70     0.78     0.82
..         ...        ...      ...      ...      ...      ...      ...
102  1554430.0  1662870.0     1.17     1.11     0.54     0.58     0.51
103  2120437.0  2316122.0     1.24     1.18     1.64     2.32     1.99
104   818811.0   864354.0     0.16     0.18     0.17     0.14     0.14
105   126394.0   132726.0     1.04     0.79     0.48     0.51     0.26
106   200920.0   232278.0     0.44     0.32     0.20     0.45     0.37

     DER2019  DER2020  DER2021  DER2022  DER2023  CR2014  CR2015  CR2016  \
0       0.00     0.00     0.01     0.01     0.01    1.17    0.90    0.86
1       0.04     0.03     0.05     0.00     0.09    3.96    4.31    5.40
2       0.88     0.81     0.71     0.84     0.22    0.49    0.59    0.53
3       1.19     4.84     1.31     1.33     1.50    0.79    0.57    0.64
4       0.84     1.18     0.59     0.45     0.36    2.34    2.08    1.75
..       ...      ...      ...      ...      ...     ...     ...     ...
102     0.54     0.66     0.50     0.59     0.78    0.35    0.39    0.51
103     2.02    15.80      NaN      NaN      NaN    0.34    0.92    0.28
104     0.10     0.13     0.15     0.16     0.10    2.15    2.24    2.85
105     0.16     0.09     0.05     0.01     0.03    3.94    3.60    4.19
106     0.42     0.33     0.31     0.20     0.35    1.17    1.23    1.30

     CR2017  CR2018  CR2019  CR2020  CR2021  CR2022  CR2023  PER2014  PER2015  \
0      0.94    1.06    1.24    1.49    1.63    1.61    1.29    32.67    32.32
1      5.96    6.18    8.05   10.11    6.14    9.84    4.96    16.75    28.52
2      0.57    0.65    0.77    0.77    0.62    0.67    0.42      NaN   167.32
3      0.79    0.77    0.76    0.67    0.80    0.81    0.91      NaN      NaN
4      2.25    1.51    1.28    1.23    1.92    2.79    2.40    38.23    57.56
..      ...     ...     ...     ...     ...     ...     ...      ...      ...
102    0.66    0.50    0.46    0.39    0.54    0.66    0.58      NaN    29.41
103    0.36    0.81    0.23    0.15    0.14    0.17    0.13    28.17    23.55
104    3.39    2.73    2.85    2.62    2.17    2.09    2.70    18.41    19.17
105    5.23    4.46    3.12    3.97    5.26    5.27    4.28    34.00    53.60
106    0.65    1.13    1.34    1.24    0.87    1.18    1.77    23.71    28.13

     PER2016  PER2017  PER2018  PER2019  PER2020  PER2021  PER2022  PER2023  \
0      43.92    43.62    31.71    31.91    12.26    19.60    23.54    42.40
1      14.39    35.87    31.15    32.24    15.79    39.75    26.33    28.28
2      15.69    50.87   145.65    70.48    38.32   228.29   321.49   118.33
3        NaN   215.85   425.01    72.73      NaN      NaN      NaN   183.24
4      50.94    56.89    66.87    58.97    31.05      NaN   112.05    56.94
..       ...      ...      ...      ...      ...      ...      ...      ...
102     1.99     8.43    11.20    10.52     4.36     8.17     9.59     4.46
103    15.11      NaN      NaN      NaN      NaN      NaN      NaN      NaN
104    17.29    16.33    16.34    18.58    12.95    22.97    26.97    20.81
105    57.02    57.31    39.06    21.89    15.43    17.07    19.93    26.46
106    15.92    68.31    29.32    23.51    19.40    27.09    30.31    30.26

     PBR2014  PBR2015  PBR2016  PBR2017  PBR2018  PBR2019  PBR2020  PBR2021  \
0       3.20     3.46     2.99     3.00     3.02     3.05     1.57     2.76
1       4.02     7.15     4.32     6.18     5.08     5.64     3.64     4.73
2       4.03     6.59     2.29     3.17     4.41     4.01     4.02    27.47
3       1.32     3.09    12.46    12.41    12.11    14.07    10.90     6.97
4       4.30     6.03     5.58     4.61     4.01     4.51     3.97     8.02
..       ...      ...      ...      ...      ...      ...      ...      ...
102     1.67     1.66     0.34     1.02     1.41     0.89     0.34     1.11
103     2.93     3.02     1.60     1.30     1.23     1.03     0.99      NaN
104     4.56     4.48     3.44     2.71     3.12     3.23     2.42     5.02
105    13.36    12.78    10.30    11.83     9.80     6.21     1.56     2.23
106     5.78     7.88     5.17     6.84     5.18     4.07     2.43     3.54

     PBR2022  PBR2023  ROA2014  ROA2015  ROA2016  ROA2017  ROA2018  ROA2019  \
0       2.76     2.23     3.94     2.74     7.33    12.70    13.40    14.61
1       3.33     5.00     1.78     2.02     2.39     3.14     3.56     2.36
2      46.84    14.32    10.84     6.79     5.89     5.77     4.81     6.14
3       9.84     6.14     4.38     5.75     5.79     6.18     5.84     9.36
4      10.63     8.95     4.07     1.97     3.16     3.58     3.51     2.13
..       ...      ...      ...      ...      ...      ...      ...      ...
102     1.93     1.50    23.00    13.33    13.60    14.09    15.13    12.22
103      NaN      NaN    11.73    16.71    15.97    14.64    17.88    10.63
104     5.97     3.19     0.60     2.84     0.03     3.39    10.99     5.07
105     2.81     2.10     5.02     5.38     4.46     6.85    10.05    10.95
106     2.69     3.65     7.78     2.25    -0.41     0.86     1.02    -1.16

     ROA2020  ROA2021  ROA2022  ROA2023
0      13.33    10.66     5.16     8.26
1       2.37     3.65     1.67     4.41
2       6.22     7.27     8.84     9.47
3      12.83    12.12    11.68    11.26
4       0.41     1.11     2.94     1.92
..       ...      ...      ...      ...
102    12.53    10.70     9.84    11.73
103     7.00     6.16     2.74     2.90
104     8.88     6.54     3.79     3.32
105    12.57     8.08     6.96    10.11
106    -0.26    -1.56     0.14     4.67

[107 rows x 141 columns]>

In [66]:
def transform_data(df, value_columns):
    # Reshaping the DataFrame for each set of value columns
    melted_dfs = []
    for col_prefix in value_columns:
        melted_df = pd.melt(df, id_vars='Company Name', var_name='year', value_name=col_prefix)
        #melted_df['year'] = melted_df['year'].str.extract('(\d+)', expand=False).astype(float)
        #melted_df['year'] = range
        melted_dfs.append(melted_df)
    
    # Merging the melted DataFrames
    result_df = melted_dfs[0]
    for melted_df in melted_dfs[1:]:
        result_df = pd.merge(result_df, melted_df, on=['Company Name'])
    
    # Sorting the DataFrame
    result_df = result_df.sort_values(by=['Company Name']).reset_index(drop=True)
    
    return result_df

In [67]:
col_names_list

['PER',
 'GD',
 'LTA',
 'CD',
 'BI',
 'ESGS',
 'TQ',
 'ROA',
 'PBR',
 'CR',
 'BS',
 'TA',
 'ESGC',
 'DER']

In [69]:
df = data.loc[:2,["Company Name", 'TQ2014', "TQ2015", "LTA2014", "LTA2015"]]
#df =  df.T
print(df)
col_names_list = ['TQ', 'LTA']

             Company Name    TQ2014    TQ2015   LTA2014   LTA2015
0              A C C Ltd.  2.130143  2.274329  5.091727  5.111278
1  A I A Engineering Ltd.  3.184262  5.879729  4.228447  4.306322
2  Adani Enterprises Ltd.  2.073602  3.236987  5.355831  5.357331

In [36]:
#output_df = transform_data(df=df, value_columns=col_names_list)

In [71]:
import pandas as pd

# Create a DataFrame from the provided data
'''
data = {
    'Company Name': ['A C C Ltd.', 'A I A Engineering Ltd.'],
    'TQ2014': [2.130143089, 3.184261722],
    'TQ2015': [2.274329494, 5.879728528],
    'TQ2016': [1.989409051, 3.713890225],
    'TY2014': [1, 4],
    'TY2015': [2, 5],
    'TY2016': [3, 6]
}
'''

#df = pd.DataFrame(data)

# Initialize an empty list to store transformed rows
transformed_rows = []

# Iterate over the rows of the DataFrame
for index, row in df.iterrows():
    company_name = row['Company Name']
    
    # Iterate over the columns of the row
    for col_name, value in row.items():
        if col_name.startswith('TQ') or col_name.startswith('LTA'):
            year = col_name[2:]
            variable = col_name[:2]
            transformed_rows.append([company_name, year, value, variable])

# Create a DataFrame from the transformed rows
transformed_df = pd.DataFrame(transformed_rows, columns=['Company Name', 'year', 'value', 'variable'])

# Pivot the DataFrame to get separate TQ and TY columns
final_df = transformed_df.pivot_table(index=['Company Name', 'year'], columns='variable', values='value').reset_index()

# Display the transformed DataFrame
print(final_df)

variable            Company Name   year        LT        TQ
0                     A C C Ltd.   2014       NaN  2.130143
1                     A C C Ltd.   2015       NaN  2.274329
2                     A C C Ltd.  A2014  5.091727       NaN
3                     A C C Ltd.  A2015  5.111278       NaN
4         A I A Engineering Ltd.   2014       NaN  3.184262
..                           ...    ...       ...       ...
7         A I A Engineering Ltd.  A2015  4.306322       NaN
8         Adani Enterprises Ltd.   2014       NaN  2.073602
9         Adani Enterprises Ltd.   2015       NaN  3.236987
10        Adani Enterprises Ltd.  A2014  5.355831       NaN
11        Adani Enterprises Ltd.  A2015  5.357331       NaN

[12 rows x 4 columns]